from fastapi import Depends, FastAPI

from ai_research_assistant.dependencies import get_chat_service
from ai_research_assistant.schemas.chat import ChatRequest, ChatResponse
from ai_research_assistant.services.chat_service import ChatService

app = FastAPI(
    title="AI Research Assistant",
    description="AI-powered research and knowledge assistant.",
    version="0.1.0",
)

@app.get("/")
def root():
    return {"message": "AI Research Assistant"}

@app.post(
    "/chat",
    response_model=ChatResponse,
    summary="Send a message to the AI assistant",
    description="Send a message to the AI assistant and receive a response generated by the configured LLM provider.",
)
def chat(
    request: ChatRequest,
    service: ChatService = Depends(get_chat_service),
):
    response = service.chat(request.message)

    return ChatResponse(response=response)